### ISSUE TITLE
Misc bugs / updates required for this sample

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/appengine-vm-fortunespeak-python#30]
The components update command in [README](https://github.com/GoogleCloudPlatform/appengine-vm-fortunespeak-python/blame/master/README.md#L53) fails:
```
$ gcloud components update appengine-managed-vms
ERROR: (gcloud.components.update) The following components are unknown [appengine-managed-vms]
```

**Comment by bshaffer** [comment]
In addition the `Dockerfile` for all step files is incorrect for step2 through step6 - the line [here](https://github.com/GoogleCloudPlatform/appengine-vm-fortunespeak-python/blob/step2/Dockerfile#L3) should be `gcr.io/google_appengine/python-compat` and not `google/appengine-python27`

**Comment by bbodenmiller** [comment]
At step 5 I don't think the pip command is correct as all I'm getting is `no module named flask errors` messages.

**Comment by theacodes** [comment]
Closing. This repository is deprecated.
